### ISSUE TITLE
Can't start project locally 

### ISSUE THREAD

**Issue by hediinn** [flowcore-io/open-source-conference-app#1]
what I did first, i tried containerized: 
                - cloned
                - podman build -f Dockerfile --format docker
                didn't work
so I tried:
              - install npm
              - npm install
              -  run ./scripts start-local-db.sh
              - edit  .env to say:

POSTGRES_URL="localhost"
POSTGRES_PRISMA_URL=
POSTGRES_URL_NON_POOLING=
POSTGRES_USER="root"
POSTGRES_HOST="localhost"
POSTGRES_PASSWORD="1234"
POSTGRES_DATABASE=

I think the defaults are not the best...... at least give a example for what the .env should look like....... what is the default postgress user i'm guessing root.......
and the requierments to get the project running, 
I think there need's to be looked at writing a better startup script or 
maybe just use docker-compose......

**Comment by olavurellefsen** [comment]
.env.example has the following additional environmental variables

```
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY=
CLERK_SECRET_KEY=

FLOWCORE_DATACORE=
FLOWCORE_KEY=

```

In order to get these variables, the project needs to be set up on [Clerk](https://clerk.com) and [Flowcore](https://flowcore.io/).

Regarding the two Flowcore environmental variables, it is the datacore url (in the format https://webhook.api.flowcore.io/event/orgname/datacoreuuid, where orgname is your organization's slug and datacoreuuid is the uuid of your datacore) and the organization' api key (found at the bottom of e.g. https://flowcore.io/orgname/settings, where orgname is your organization's slug).

Agree that this should be better explained in the .env.example
